<a href="https://colab.research.google.com/github/dharshdk/DL/blob/main/Titanic_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras import layers, models

In [ ]:
train_data = pd.read_csv('/content/train.csv')
train_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
test_data = pd.read_csv('/content/test.csv')
test_data

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
train_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
test_data.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
train_data = train_data.drop(['Name',  'Cabin'], axis=1)
test_data = test_data.drop(['Name',  'Cabin'], axis=1)

In [ ]:
train_data['Age'].fillna(train_data['Age'].mean(), inplace=True)
train_data['Embarked'].fillna(train_data['Embarked'].mode()[0], inplace=True)
train_data['Fare'].fillna(train_data['Fare'].mean(), inplace=True)

In [ ]:
test_data['Age'].fillna(test_data['Age'].mean(), inplace=True)
test_data['Embarked'].fillna(test_data['Embarked'].mode()[0], inplace=True)
test_data['Fare'].fillna(test_data['Fare'].mean(), inplace=True)

In [ ]:
train_data

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,female,35.000000,1,0,113803,53.1000,S
4,5,0,3,male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.000000,0,0,211536,13.0000,S
887,888,1,1,female,19.000000,0,0,112053,30.0000,S
888,889,0,3,female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,male,26.000000,0,0,111369,30.0000,C
890,891,0,3,male,32.000000,0,0,370376,7.7500,Q

In [ ]:
test_data

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,male,34.50000,0,0,330911,7.8292,Q
1,893,3,female,47.00000,1,0,363272,7.0000,S
2,894,2,male,62.00000,0,0,240276,9.6875,Q
3,895,3,male,27.00000,0,0,315154,8.6625,S
4,896,3,female,22.00000,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...
413,1305,3,male,30.27259,0,0,A.5. 3236,8.0500,S
414,1306,1,female,39.00000,0,0,PC 17758,108.9000,C
415,1307,3,male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,3,male,30.27259,0,0,359309,8.0500,S
417,1309,3,male,30.27259,1,1,2668,22.3583,C

In [ ]:
test_data["Sex"],class_name = pd.factorize(test_data["Sex"])
test_data["Ticket"],class_name = pd.factorize(test_data["Ticket"])
test_data["Embarked"],class_name = pd.factorize(test_data["Embarked"])

In [ ]:
train_data["Sex"],class_name = pd.factorize(train_data["Sex"])
train_data["Ticket"],class_name = pd.factorize(train_data["Ticket"])
train_data["Embarked"],class_name = pd.factorize(train_data["Embarked"])

In [ ]:
test_data

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,0,34.50000,0,0,0,7.8292,0
1,893,3,1,47.00000,1,0,1,7.0000,1
2,894,2,0,62.00000,0,0,2,9.6875,0
3,895,3,0,27.00000,0,0,3,8.6625,1
4,896,3,1,22.00000,1,1,4,12.2875,1
...,...,...,...,...,...,...,...,...,...
413,1305,3,0,30.27259,0,0,358,8.0500,1
414,1306,1,1,39.00000,0,0,359,108.9000,2
415,1307,3,0,38.50000,0,0,360,7.2500,1
416,1308,3,0,30.27259,0,0,361,8.0500,1
417,1309,3,0,30.27259,1,1,362,22.3583,2

In [ ]:
train_data

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,0,22.000000,1,0,0,7.2500,0
1,2,1,1,1,38.000000,1,0,1,71.2833,1
2,3,1,3,1,26.000000,0,0,2,7.9250,0
3,4,1,1,1,35.000000,1,0,3,53.1000,0
4,5,0,3,0,35.000000,0,0,4,8.0500,0
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,0,27.000000,0,0,677,13.0000,0
887,888,1,1,1,19.000000,0,0,678,30.0000,0
888,889,0,3,1,29.699118,1,2,614,23.4500,0
889,890,1,1,0,26.000000,0,0,679,30.0000,1
890,891,0,3,0,32.000000,0,0,680,7.7500,2

In [ ]:
X_train = train_data.drop("Survived", axis=1)
y_train = train_data["Survived"]

In [ ]:
#X_train_split, X_test_split, y_train_split, y_test_split = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [ ]:
model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=20, batch_size=34, validation_split=0.2)

Epoch 1/20
21/21 [==============================] - 1s 14ms/step - loss: 2.7365 - accuracy: 0.5632 - val_loss: 3.5347 - val_accuracy: 0.6704
Epoch 2/20
21/21 [==============================] - 0s 5ms/step - loss: 1.0250 - accuracy: 0.5604 - val_loss: 2.1361 - val_accuracy: 0.6369
Epoch 3/20
21/21 [==============================] - 0s 3ms/step - loss: 0.9873 - accuracy: 0.6011 - val_loss: 2.1526 - val_accuracy: 0.6760
Epoch 4/20
21/21 [==============================] - 0s 4ms/step - loss: 0.7939 - accuracy: 0.6081 - val_loss: 0.6985 - val_accuracy: 0.6872
Epoch 5/20
21/21 [==============================] - 0s 4ms/step - loss: 0.6808 - accuracy: 0.6671 - val_loss: 0.7053 - val_accuracy: 0.6648
Epoch 6/20
21/21 [==============================] - 0s 3ms/step - loss: 0.6827 - accuracy: 0.6756 - val_loss: 0.7989 - val_accuracy: 0.5307
Epoch 7/20
21/21 [==============================] - 0s 3ms/step - loss: 0.7041 - accuracy: 0.6601 - val_loss: 1.4405 - val_accuracy: 0.6704
Epoch 8/20
21/21 [==============================] - 0s 4ms/step - loss: 0.8132 - accuracy: 0.6110 - val_loss: 1.6531 - val_accuracy: 0.6816
Epoch 9/20
21/21 [==============================] - 0s 4ms/step - loss: 0.7007 - accuracy: 0.6419 - val_loss: 1.1892 - val_accuracy: 0.6983
Epoch 10/20
21/21 [==============================] - 0s 4ms/step - loss: 0.6449 - accuracy: 0.6699 - val_loss: 0.6061 - val_accuracy: 0.6648
Epoch 11/20
21/21 [==============================] - 0s 3ms/step - loss: 0.6014 - accuracy: 0.7121 - val_loss: 0.9597 - val_accuracy: 0.6704
Epoch 12/20
21/21 [==============================] - 0s 4ms/step - loss: 0.6886 - accuracy: 0.6475 - val_loss: 1.1303 - val_accuracy: 0.3855
Epoch 13/20
21/21 [==============================] - 0s 3ms/step - loss: 0.6914 - accuracy: 0.6615 - val_loss: 0.6556 - val_accuracy: 0.6872
Epoch 14/20
21/21 [==============================] - 0s 4ms/step - loss: 0.5912 - accuracy: 0.7107 - val_loss: 0.6276 - val_accuracy: 0.7430
Epoch 15/20
21/21 [==============================] - 0s 3ms/step - loss: 0.5457 - accuracy: 0.7374 - val_loss: 0.5553 - val_accuracy: 0.6872
Epoch 16/20
21/21 [==============================] - 0s 4ms/step - loss: 0.5612 - accuracy: 0.7093 - val_loss: 0.5410 - val_accuracy: 0.7486
Epoch 17/20
21/21 [==============================] - 0s 4ms/step - loss: 0.5702 - accuracy: 0.7303 - val_loss: 0.5756 - val_accuracy: 0.7207
Epoch 18/20
21/21 [==============================] - 0s 4ms/step - loss: 0.5291 - accuracy: 0.7458 - val_loss: 0.5270 - val_accuracy: 0.7263
Epoch 19/20
21/21 [==============================] - 0s 4ms/step - loss: 0.6314 - accuracy: 0.7065 - val_loss: 0.8149 - val_accuracy: 0.6983
Epoch 20/20
21/21 [==============================] - 0s 3ms/step - loss: 0.9488 - accuracy: 0.6461 - val_loss: 1.4522 - val_accuracy: 0.6983

In [ ]:
predictions = model.predict(test_data)
predictions = (predictions > 0.5).astype(int)

14/14 [==============================] - 0s 1ms/step

In [ ]:
submission_df = pd.DataFrame({
    "PassengerId": test_data["PassengerId"],
    "Survived": predictions.flatten()
})

In [ ]:
submission_df.to_csv("submission.csv", index=False)

In [ ]:
from google.colab import files
files.download("/content/submission.csv")